const URI_QUESTION_SVC = process.env.URI_QUESTION_SVC || 'http://localhost:8002'

const PREFIX_QUESTION_SVC = '/api/question'

const PREFIX_ROOMQUESTION_SVC = '/roomquestion'

export const URL_QUESTION_SVC = URI_QUESTION_SVC + PREFIX_QUESTION_SVC

export const URL_ROOMQUESTION_SVC = URI_QUESTION_SVC + PREFIX_QUESTION_SVC + PREFIX_ROOMQUESTION_SVC